# Generated by Django 6.0.3 on 2026-06-15 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_email_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('announcement_type', models.CharField(choices=[('announcement', 'Announcement'), ('meeting', 'Meeting')], default='announcement', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement', to='api.meeting')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
