# Generated by Django 6.0.3 on 2026-06-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodLog',
        ),
    ]
