# Generated by Django 6.0.3 on 2026-06-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_moodlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='mood',
            field=models.CharField(blank=True, choices=[('focused', 'Focused'), ('energized', 'Energized'), ('tired', 'Tired'), ('stressed', 'Stressed')], max_length=20, null=True),
        ),
    ]
